AllCops:
  EnabledByDefault: true
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Copyright:
  AutocorrectNotice: |
    # Copyright (c) 2022 Steven Hoffman
    # All rights reserved.
  Notice: '^# Copyright \(c\) 2022 .+'

Naming/FileName:
  Exclude:
    - lib/fustrate-rails.rb

# ------------------------------------------------------------------------------
# Cops that should not be run
# ------------------------------------------------------------------------------

# Recommends right hand side of multi-line assignment be on a new line
Layout/MultilineAssignmentLayout:
  Enabled: false

# Recommends squishing a multi-line hash into one line. I don't like that. It's not readable.
Layout/RedundantLineBreak:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false
