AllCops:
  EnabledByDefault: true
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Copyright:
  AutocorrectNotice: |
    # Copyright (c) 2021 Steven Hoffman
    # All rights reserved.
  Notice: '^# Copyright \(c\) 2021 .+'

Naming/FileName:
  Exclude:
    - lib/fustrate-rails.rb

# ------------------------------------------------------------------------------
# Cops that should not be run
# ------------------------------------------------------------------------------

# Recommends right hand side of multi-line assignment be on a new line
Layout/MultilineAssignmentLayout:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false
