inherit_from:
  - config/rubocop/default.yml

Style/Copyright:
  AutocorrectNotice: |
    # Copyright (c) Steven Hoffman
    # All rights reserved.
  Notice: |
    Copyright \(c\) Steven Hoffman
    All rights reserved.

Naming/FileName:
  Exclude:
    - lib/fustrate-rails.rb

# Every class and module *should* be documented, but I don't have the time
Style/Documentation:
  Enabled: false

# Every method *should* be documented, but I don't have the time
Style/DocumentationMethod:
  Enabled: false

# I'd rather just have the :: there and be done with it.
Style/RedundantConstantBase:
  Enabled: false
