scss_files: 'vendor/assets/stylesheets/**/*.scss'

exclude: 'vendor/assets/stylesheets/vendor/**'

linters:
  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  QualifyingElement:
    enabled: false

  VendorPrefix:
    enabled: false
